INSERT INTO shops (id, name, description, category, tags, latitude, longitude, trend_score, is_ad_contracted) VALUES 
(gen_random_uuid(), 'After You Dessert Cafe', 'Famous for Shibuya Honey Toast and Kakigori.', 'Dessert', 'Cafe, Dessert, Sweets, Bingsu', 13.7288, 100.5348, 98, false),
(gen_random_uuid(), 'Khao San Road Night Market', 'Vibrant night market popular among backpackers.', 'Street Food', 'Night Market, Backpackers, Drinks', 13.7590, 100.4971, 95, false),
(gen_random_uuid(), 'PTT Station Vibhavadi', 'Large gas station with Amazon Cafe and food courts.', 'Gas Station', 'Fuel, Rest Area, Cafe Amazon', 13.8203, 100.5601, 75, true),
(gen_random_uuid(), 'Gaggan Anand', 'Renowned progressive Indian cuisine restaurant.', 'Restaurant', 'Fine Dining, Indian, Michelin', 13.7383, 100.5427, 99, false),
(gen_random_uuid(), 'Tichuca Rooftop Bar', 'Jungle-themed rooftop bar with glowing jellyfish tree.', 'Cafe', 'Rooftop, Bar, Nightlife', 13.7215, 100.5815, 96, true),
(gen_random_uuid(), 'Roast at EmQuartier', 'Cozy cafe known for specialty coffee and brunch.', 'Cafe', 'Brunch, Coffee, EmQuartier', 13.7314, 100.5697, 88, false),
(gen_random_uuid(), 'Jay Fai', 'Michelin-starred street food stall famous for crab omelet.', 'Street Food', 'Michelin, Seafood, Historic', 13.7526, 100.5048, 100, false),
(gen_random_uuid(), 'Siam Paragon Food Hall', 'Luxurious food court offering diverse cuisines.', 'Restaurant', 'Food Court, Mall, Diverse', 13.7468, 100.5346, 92, true),
(gen_random_uuid(), 'Shell Station Bangna', 'Convenient rest stop with Deli Cafe and minimart.', 'Gas Station', 'Fuel, Minimart, Rest Stop', 13.6705, 100.6128, 68, false),
(gen_random_uuid(), 'Chatuchak Weekend Market', 'Massive market with thousands of food and clothing stalls.', 'Street Food', 'Market, Shopping, Weekend', 13.7999, 100.5509, 97, false),
(gen_random_uuid(), 'Thip Samai Pad Thai', 'Legendary Pad Thai restaurant with a long history.', 'Restaurant', 'Pad Thai, Noodles, Famous', 13.7527, 100.5048, 93, false),
(gen_random_uuid(), 'Mandarin Oriental Bangkok', 'Historic luxury hotel along the Chao Phraya River.', 'Hotel', 'Luxury, Historic, Riverside', 13.7235, 100.5142, 94, true),
(gen_random_uuid(), 'The Commons Thonglor', 'Community mall with trendy cafes and eateries.', 'Cafe', 'Trendy, Brunch, Community', 13.7335, 100.5826, 90, false),
(gen_random_uuid(), 'Som Tum Der', 'Authentic Isan cuisine, famous for Som Tum.', 'Restaurant', 'Isan, Spicy, Som Tum', 13.7289, 100.5332, 89, false),
(gen_random_uuid(), 'Bangchak Station Sukhumvit', 'Eco-friendly gas station with Inthanin Coffee.', 'Gas Station', 'Eco, Fuel, Coffee', 13.7042, 100.6034, 70, false),
(gen_random_uuid(), 'Cabbages & Condoms', 'Unique restaurant promoting family planning.', 'Restaurant', 'Unique, Thai Food, Concept', 13.7380, 100.5583, 86, true),
(gen_random_uuid(), 'Asiatique The Riverfront', 'Open-air mall with dining, shopping, and entertainment.', 'Restaurant', 'Riverfront, Dining, Shopping', 13.7046, 100.5033, 91, false),
(gen_random_uuid(), 'Red Sky Bar', 'Rooftop bar offering panoramic views of Bangkok.', 'Cafe', 'Rooftop, Views, Cocktails', 13.7466, 100.5393, 88, true),
(gen_random_uuid(), 'PTT Life Station Rama 2', 'Modern gas station with lifestyle amenities.', 'Gas Station', 'Modern, Amenities, Fuel', 13.6664, 100.4357, 72, false),
(gen_random_uuid(), 'Blue Elephant', 'Fine dining Thai restaurant in a historic mansion.', 'Restaurant', 'Fine Dining, Historic, Thai', 13.7171, 100.5218, 95, false);